// Generated by js_of_ocaml
//# buildInfo:effects=false, use-js-string=false, version=5.0.1
(function
   (globalThis)
   {"use strict";
    var
     runtime=globalThis.jsoo_runtime,
     caml_register_global=runtime.caml_register_global;
    function caml_call1(f,a0)
     {return f.length == 1?f(a0):runtime.caml_call_gen(f,[a0])}
    function caml_call2(f,a0,a1)
     {return f.length == 2?f(a0,a1):runtime.caml_call_gen(f,[a0,a1])}
    var Util=[0],Util$0=[0,Util];
    caml_register_global(0,Util$0,"Util__");
    function symbol(f,g,x){return caml_call1(f,caml_call1(g,x))}
    function symbol$0(f,g,x,y){return caml_call1(f,caml_call2(g,x,y))}
    var include=[0,symbol,symbol$0];
    caml_register_global(1,include,"Util__Combinator");
    var Util$1=[0,symbol,symbol$0];
    caml_register_global(2,Util$1,"Util");
    return}
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiIudXRpbC5vYmpzL3V0aWwuY21hLmpzIiwic291cmNlUm9vdCI6IiIsIm5hbWVzIjpbInN5bWJvbCIsImYiLCJnIiwieCIsInN5bWJvbCQwIiwieSJdLCJzb3VyY2VzIjpbIi93b3Jrc3BhY2Vfcm9vdC91dGlsL3V0aWxfXy5tbC1nZW4iLCIvd29ya3NwYWNlX3Jvb3QvdXRpbC9jb21iaW5hdG9yLm1sIl0sIm1hcHBpbmdzIjoiOzs7OztJOzs7Ozs7O0lBS2dCOzthQ0xaQSxPQUFPQyxFQUFFQyxFQUFFQyxHQUFNLGtCQUFWRixFQUFVLFdBQVJDLEVBQUVDLEdBQVc7YUFDdEJDLFNBQVFILEVBQUVDLEVBQUVDLEVBQUVFLEdBQU0sa0JBQVpKLEVBQVksV0FBVkMsRUFBRUMsRUFBRUUsR0FBYTttQkFEM0JMLE9BQ0FJOztrQkFEQUosT0FDQUk7O1UiLCJzb3VyY2VzQ29udGVudCI6WyIoKiBnZW5lcmF0ZWQgYnkgZHVuZSAqKVxuXG4oKiogQGNhbm9uaWNhbCBVdGlsLkNvbWJpbmF0b3IgKilcbm1vZHVsZSBDb21iaW5hdG9yID0gVXRpbF9fQ29tYmluYXRvclxuXG5tb2R1bGUgVXRpbF9fID0gc3RydWN0IGVuZFxuW0BAZGVwcmVjYXRlZCBcInRoaXMgbW9kdWxlIGlzIHNoYWRvd2VkXCJdXG4iLCJsZXQgKCA8LiApIGYgZyB4ID0gZiAoZyB4KVxubGV0ICggPC4uICkgZiBnIHggeSA9IGYgKGcgeCB5KVxuIl19
