// Generated by js_of_ocaml
//# buildInfo:effects=false, use-js-string=false, version=5.0.1
(function
   (globalThis)
   {"use strict";
    var runtime=globalThis.jsoo_runtime;
    function caml_call2(f,a0,a1)
     {return f.length == 2?f(a0,a1):runtime.caml_call_gen(f,[a0,a1])}
    var
     global_data=runtime.caml_get_global_data(),
     cst_LinearTypes=runtime.caml_string_of_jsbytes("LinearTypes"),
     Util=global_data.Util;
    global_data.CamlinternalOO;
    var
     Stdlib_Lexing=global_data.Stdlib__Lexing,
     Preproc_Lexer=global_data.Preproc__Lexer,
     Preproc_Parser=global_data.Preproc__Parser,
     Preproc_Exec=global_data.Preproc__Exec,
     Js_of_ocaml_Js=global_data.Js_of_ocaml__Js;
    function code(str)
     {var _a_=caml_call2(Stdlib_Lexing[3],0,str);
      return caml_call2(Preproc_Parser[2],Preproc_Lexer[2],_a_)}
    var
     exec_js=caml_call2(Util[1],Preproc_Exec[4],code),
     exec_js$0=caml_call2(Util[1],runtime.caml_jsstring_of_string,exec_js);
    function t0(param)
     {return caml_call2(Util[1],exec_js$0,runtime.caml_string_of_jsstring)}
    caml_call2
     (Js_of_ocaml_Js[50],
      cst_LinearTypes,
      {"run":runtime.caml_js_wrap_meth_callback(t0)});
    var Dune_exe_Js=[0];
    runtime.caml_register_global(12,Dune_exe_Js,"Dune__exe__Js");
    return}
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiIuanMuZW9ianMvYnl0ZS9kdW5lX19leGVfX0pzLmNtby5qcyIsInNvdXJjZVJvb3QiOiIiLCJuYW1lcyI6WyJjb2RlIiwic3RyIiwiZXhlY19qcyIsImV4ZWNfanMkMCJdLCJzb3VyY2VzIjpbIi93b3Jrc3BhY2Vfcm9vdC9qcy9qcy5tbCJdLCJtYXBwaW5ncyI6Ijs7Ozs7STs7Ozs7Ozs7Ozs7Ozs7YUFJSUEsS0FBS0M7TUFBaUMsc0NBQWpDQTtNQUFpQyx5REFBd0I7SUFFbkQ7Z0RBRlhEO0tBY1UsNkRBWlZFO0lBWVU7TUFLTSwwQkFMaEJDLDBDQUt1QztJQUZ6Qzs7Ozs7O1UiLCJzb3VyY2VzQ29udGVudCI6WyJvcGVuIFByZXByb2Ncbm9wZW4gVXRpbCBcbm9wZW4gSnNfb2Zfb2NhbWxcblxubGV0IGNvZGUgc3RyID0gUGFyc2VyLnRvcGxldmVsIExleGVyLm1haW4gKExleGluZy5mcm9tX3N0cmluZyBzdHIpXG5cbmxldCBleGVjX2pzJyA9IEV4ZWMuZXhlYyA8LiBjb2RlXG5cbigqXG5sZXQgZXhlY19qcycgY29kZSBzdHIgPVxuICBsZXQgY29uID0gRXhlYy5leGVjX2FzdCAoY29kZSBzdHIpIFtdIGluXG4gIGxldCB1bnVzZWQgPSBMaXN0LmZpbHRlciAoZnVuIChzLHgpIC0+IFR5cGVjaGVjay5nZXRfcXVhbGlmaWVyIHggPSBBc3QuTGluICYmIHMgPD4gXCJtYWluXCIpIGNvbiBpblxuICBpZiBMaXN0Lmxlbmd0aCB1bnVzZWQgPSAwIHRoZW4gQXN0LmNvbnRleHRfb2Zfc3RyaW5nIGNvbiBcIlwiXG4gIGVsc2UgXCJcIlxuICAqKVxuICAoKmVsc2UgcmFpc2UgKFR5cGVjaGVjay5VblVzZShmc3QgKExpc3QuaGQgdW51c2VkKSkpOyopXG4gXG5cbmxldCBleGVjX2pzID0gSnMuc3RyaW5nIDwuIGV4ZWNfanMnXG5cbmxldCAoKSA9XG4gIEpzLmV4cG9ydCBcIkxpbmVhclR5cGVzXCJcbiAgICAob2JqZWN0JWpzXG4gICAgICAgbWV0aG9kIHJ1biA9IGV4ZWNfanMgPC4gSnMudG9fc3RyaW5nXG4gICAgZW5kKVxuXG4iXX0=
